export const newItem = {
    available: false,
    name: "New Cargo",
    label: "NEWC",
    abbreviation: "NE",
    colour: 1,
    unitName: "Items",
    longName: "items",
    classes: 0x20,
    weight: 16,
    price: 4112,
    penaltyLowerBound: 0,
    penaltyLength: 255,
    sprite: {
        base64Data: "",
        width: 10,
        height: 10,
        left: 0,
        top: 0,
    },
};
