export const config = {
    general: { grfid: "TRU1", name: "TrueGRF", description: "Your first NewGRF with TrueGRF" },
    industries: [
    ],
    cargoes: [
        {
            id: 0,
            available: true,
            name: "Passengers",
            label: "PASS",
            unitName: "Passengers",
            longName: "passengers",
            classes: 1,
            weight: 1,
            price: 3185,
            penaltyLowerBound: 0,
            penaltyLength: 24,
            sprite: {
                width: 10,
                height: 10,
                top: 0,
                left: 0,
                base64Data: "",
            },
        },
        {
            id: 2,
            available: true,
            name: "Mail",
            label: "MAIL",
            unitName: "Bags",
            longName: "of mail",
            classes: 2,
            weight: 4,
            price: 4550,
            penaltyLowerBound: 20,
            penaltyLength: 90,
            sprite: {
                width: 10,
                height: 10,
                top: 0,
                left: 0,
                base64Data: "",
            },
        },
        {
            id: 5,
            available: true,
            name: "Goods",
            label: "GOOD",
            unitName: "Crates",
            longName: "of goods",
            classes: 4,
            weight: 8,
            price: 6144,
            penaltyLowerBound: 5,
            penaltyLength: 28,
            sprite: {
                width: 10,
                height: 10,
                top: 0,
                left: 0,
                base64Data: "",
            },
        },
        {
            id: 12,
            available: true,
            name: "Food",
            label: "FOOD",
            unitName: "Tonnes",
            longName: "of food",
            classes: 132,
            weight: 16,
            price: 5688,
            penaltyLowerBound: 0,
            penaltyLength: 30,
            sprite: {
                width: 10,
                height: 10,
                top: 0,
                left: 0,
                base64Data: "",
            },
        },
        {
            id: 20,
            available: true,
            name: "Sweets",
            label: "SWET",
            unitName: "Bags",
            longName: "of sweets",
            classes: 4,
            weight: 5,
            price: 6144,
            penaltyLowerBound: 8,
            penaltyLength: 40,
            sprite: {
                width: 10,
                height: 10,
                top: 0,
                left: 0,
                base64Data: "",
            },
        },
        {
            id: 26,
            available: true,
            name: "Fizzy Drinks",
            label: "FZDR",
            unitName: "Items",
            longName: "fizzy drinks",
            classes: 32,
            weight: 2,
            price: 6250,
            penaltyLowerBound: 30,
            penaltyLength: 5,
            sprite: {
                width: 10,
                height: 10,
                top: 0,
                left: 0,
                base64Data: "",
            },
        },
    ],
};
