name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Update release branch
      run: |
        npm version from-git --no-git-tag-version

        git config --global user.email "truegrf@truebrain.nl"
        git config --global user.name "TrueGRF"

        git add -A
        git commit -m "chore: bump version"
        git push -f origin HEAD:release/v2
